name: Run E2E tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-compiling-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew :kotlin-rpc:publishToMavenLocal
      # TODO: fix build logic so that API is built automatically
      - run: ./gradlew :e2e-tests:compiling:api:build
      # Run the server in the background.
      - run: ./gradlew :e2e-tests:compiling:run &
      # TODO: wait by checking if the server started. Now it's a waste of time
      # or it may not start yet.
      - run: sleep 30
      - run: ./gradlew :e2e-tests:compiling:jsTest
