name: Run E2E tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-compiling-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew :kotlin-rpc-gradle-plugin:publishToMavenLocal
      - run: ./gradlew :kotlin-rpc:publishToMavenLocal
      # TODO: fix build logic so that API is built automatically
      - run: ./gradlew :e2e-tests:compiling:api:build
      # Run the server in the background.
      - run: ./gradlew :e2e-tests:compiling:run &
      # TODO: wait by checking if the server started. Now it's a waste of time
      # or it may not start yet.
      - run: sleep 30
      - run: ./gradlew :e2e-tests:compiling:jsTest

  run-non-compiling-non-serializable-parameter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew :kotlin-rpc:publishToMavenLocal
      - run: ./gradlew :e2e-tests:non-compiling:not-serializable-parameter:api:build
      # TODO: It now fails during second build. Probably something's messed up in Gradle config.
      # This test verifies it holds true.
      - run: ./gradlew :e2e-tests:non-compiling:not-serializable-parameter:api:build > stdout.txt 2> stderr.txt || true
      - run: less stdout.txt | grep "FAILED"
      - run: less stderr.txt | grep "Serializer has not been found for type 'TestDataClass'"

  run-non-compiling-non-serializable-return-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew :kotlin-rpc:publishToMavenLocal
      - run: ./gradlew :e2e-tests:non-compiling:not-serializable-return-type:api:build
      # TODO: It now fails during second build. Probably something's messed up in Gradle config.
      # This test verifies it holds true.
      - run: ./gradlew :e2e-tests:non-compiling:not-serializable-return-type:api:build > stdout.txt 2> stderr.txt || true
      - run: less stdout.txt | grep "FAILED"
      - run: less stderr.txt | grep "Serializer has not been found for type 'SomeNonSerializableType'"
